# Generated by Django 5.0.14 on 2026-09-10 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bid_increment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price the seller will accept. Hidden from bidders.', max_digits=12, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('ENDED', 'Ended'), ('WINNER_VALIDATION', 'Winner Validation'), ('READY_TO_SHIP', 'Ready to Ship'), ('SETTLEMENT', 'Settlement'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_WINNER', 'No Winner')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'db_table': 'auctions_auction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'db_table': 'auctions_bid',
                'ordering': ['-amount'],
            },
        ),
    ]
